name: Create Release

on:
  push:
    tags:
      - 'v[0-9].[0-9].[0-9]'

jobs:
  create_release:

    runs-on: ubuntu-latest

    steps:
      - name: 'Create Release Page'
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          token: ${{ secrets.REPO_RELEASE_TOKEN }}
          generate_release_notes: true
