name: Test
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        # I had previously ran this with multiple versions
        # but the concurrent jobs hogged resources, need to tune
        # k8s resources if I'd like to reasonably use it
        # go-version: ['1.17', '1.18']
        go-version: ['1.17']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test
        run: |
          cd app
          go test -v .
