name: Test

on:
  push:
    tags-ignore:
      - '*'

jobs:
  test:
    runs_on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.15', '1.16', '1.17', '1.18']

    steps:
   	  - name: Checkout repo
      	uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test
        run: go test -v .